---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shihon-otomo/app-config.git
    targetRevision: HEAD
    path: demo-app/data-application/dev-env/app-of-apps/app1
  destination:
    server: http://127.0.0.1:59623/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false