---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-ui-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shihon-otomo/app-config.git
    targetRevision: HEAD
    path: demo-app/data-application/dev-env/data-ui
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false