apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ui-production
  namespace: prod-data-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: data-ui-production
  template:
    metadata:
      labels:
        app: data-ui-production
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: data-ui-production
        ports:
        - containerPort: 80
