---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: prod-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: secdevopsjourney/nginx:v0.3.0
          ports:
            - containerPort: 80