apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: dev-env
        url: https://kubernetes.default.svc
      - cluster: production
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-data-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/shihon-otomo/app-config.git
        targetRevision: main
        path: demo-app/data-application/{{cluster}}/app-of-apps
      destination:
        server: '{{url}}'
        namespace: argocd
