spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/shihon-otomo/app-config.git
    targetRevision: main
    path: demo-applications/guestbook/engineering-dev