apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD self-management
version: 0.1.0
appVersion: "3.0.0"
dependencies:
  - name: argo-cd
    version: "5.31.1" # Use the latest compatible version
    repository: https://argoproj.github.io/argo-helm
