---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-production-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shihon-otomo/app-config.git
    targetRevision: HEAD
    path: demo-app/data-application/production/app-of-apps
  destination:
    server: https://kubernetes.default.svc
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true